Repository JJinBBang-web/JJinBBang_BE, pull requests merged in 2025-05, with the labels that each got.

#50 [Feat] 사용자 조회 API 작성
  src/main/java/JJinBBang/app/domain/user/controller/UsersController.java
  src/main/java/JJinBBang/app/domain/user/dto/UserInfoResponseDto.java
  src/main/java/JJinBBang/app/domain/user/exception/InvalidTokenException.java
  src/main/java/JJinBBang/app/domain/user/service/UsersService.java
  src/main/java/JJinBBang/app/domain/user/service/UsersServiceImpl.java
  src/main/java/JJinBBang/app/global/common/enums/VerificationStatus.java
Labels: ✨ Feature

#53 [Feat #26] 관심목록 조회
  build.gradle
  src/main/java/JJinBBang/app/domain/building/controller/BookmarkController.java
  src/main/java/JJinBBang/app/domain/building/dto/BasicInfo.java
  src/main/java/JJinBBang/app/domain/building/dto/BuildingLikesDTO.java
  src/main/java/JJinBBang/app/domain/building/dto/GetUserBookmarkRequest.java
  src/main/java/JJinBBang/app/domain/building/dto/SetUserBookmarkRequest.java
  src/main/java/JJinBBang/app/domain/building/entity/AgencyLikeId.java
  src/main/java/JJinBBang/app/domain/building/entity/AgencyLikes.java
  src/main/java/JJinBBang/app/domain/building/entity/BuildingLikeId.java
  src/main/java/JJinBBang/app/domain/building/entity/BuildingLikes.java
  src/main/java/JJinBBang/app/domain/building/entity/Buildings.java
  src/main/java/JJinBBang/app/domain/building/entity/DormReviews.java
  src/main/java/JJinBBang/app/domain/building/entity/GeneralReviews.java
  src/main/java/JJinBBang/app/domain/building/entity/ReviewLikeId.java
  src/main/java/JJinBBang/app/domain/building/entity/ReviewLikes.java
  src/main/java/JJinBBang/app/domain/building/exception/BookmarkNotFoundException.java
  src/main/java/JJinBBang/app/domain/building/exception/UserBookmarkInvalidGroupException.java
  src/main/java/JJinBBang/app/domain/building/repository/AgenciesRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/AgencyLikesRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/BookmarkRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/BookmarkRepositoryImpl.java
  src/main/java/JJinBBang/app/domain/building/repository/BuildingLikesRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/BuildingsRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/DormReviewsRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/GeneralReviewsRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/ReviewLikesRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/ReviewsRepository.java
  src/main/java/JJinBBang/app/domain/building/service/BookmarkService.java
  src/main/java/JJinBBang/app/domain/building/service/BookmarkServiceImpl.java
  src/main/java/JJinBBang/app/domain/building/service/SearchInfo.java
  src/main/java/JJinBBang/app/domain/user/repository/UsersRepository.java
  src/main/java/JJinBBang/app/global/common/dto/AgencyBuildingInfo.java
  src/main/java/JJinBBang/app/global/common/dto/AgencyReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/DormitoryBuildingInfo.java
  src/main/java/JJinBBang/app/global/common/dto/DormitoryReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/GeneralBuildingInfo.java
  src/main/java/JJinBBang/app/global/common/dto/GeneralReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/InfoDto.java
  src/main/java/JJinBBang/app/global/common/dto/ReviewInfo.java
Labels: ✨ Feature

#59 [Feat #41] 건물에 대한 리뷰 목록 조회 API 구현
  src/main/java/JJinBBang/app/domain/building/controller/BuildingController.java
  src/main/java/JJinBBang/app/domain/building/dto/PageRequest.java
  src/main/java/JJinBBang/app/domain/building/dto/ReviewSummaryResponse.java
  src/main/java/JJinBBang/app/domain/building/entity/ReviewDetails.java
  src/main/java/JJinBBang/app/domain/building/entity/Reviews.java
  src/main/java/JJinBBang/app/domain/building/exception/ReviewDetailInternalException.java
  src/main/java/JJinBBang/app/domain/building/exception/ReviewInternalException.java
  src/main/java/JJinBBang/app/domain/building/repository/ReviewDetailRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/ReviewRepository.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewService.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
  src/main/java/JJinBBang/app/domain/common/dto/PaginatedResponse.java
  src/main/java/JJinBBang/app/domain/common/enums/SortType.java
  src/main/java/JJinBBang/app/global/common/dto/AgencyReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/DormitoryReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/GeneralReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/Keywords.java
  src/main/java/JJinBBang/app/global/common/dto/ReviewInfo.java
Labels: ✨ Feature, 🔨 Refactor

#61 [Feat #60] 리뷰 상세 조회 API 구현
  src/main/java/JJinBBang/app/domain/building/controller/ReviewController.java
  src/main/java/JJinBBang/app/domain/building/dto/Building.java
  src/main/java/JJinBBang/app/domain/building/dto/Conditions.java
  src/main/java/JJinBBang/app/domain/building/dto/FacilitiesDto.java
  src/main/java/JJinBBang/app/domain/building/dto/ReviewDetailResponse.java
  src/main/java/JJinBBang/app/domain/building/entity/DormReviews.java
  src/main/java/JJinBBang/app/domain/building/entity/DormitoryFacilities.java
  src/main/java/JJinBBang/app/domain/building/entity/Facilities.java
  src/main/java/JJinBBang/app/domain/building/exception/MissingReviewDetailException.java
  src/main/java/JJinBBang/app/domain/building/exception/ReviewNotFoundException.java
  src/main/java/JJinBBang/app/domain/building/exception/UnrecognizedReviewTypeException.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewService.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
  src/main/java/JJinBBang/app/global/common/dto/AgencyReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/DormitoryReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/GeneralReviewInfo.java
Labels: ✨ Feature

#65 [Feat #63] 이메일 인증 API 구현 및 인증 상태 관리 로직 수정
  src/main/java/JJinBBang/app/domain/user/controller/AuthController.java
  src/main/java/JJinBBang/app/domain/user/dto/request/IssueEmailCodeRequest.java
  src/main/java/JJinBBang/app/domain/user/dto/request/VerifyEmailCodeRequest.java
  src/main/java/JJinBBang/app/domain/user/entity/Users.java
  src/main/java/JJinBBang/app/domain/user/service/UsersService.java
  src/main/java/JJinBBang/app/domain/user/service/UsersServiceImpl.java
  src/main/java/JJinBBang/app/global/mail/dto/EmailAuthInfo.java
  src/main/java/JJinBBang/app/global/mail/exception/MailInvalidException.java
  src/main/java/JJinBBang/app/global/mail/exception/MailNotFoundException.java
  src/main/java/JJinBBang/app/global/mail/repository/EmailAuthCodeRepository.java
  src/main/java/JJinBBang/app/global/mail/repository/InMemoryEmailAuthCodeRepository.java
  src/main/java/JJinBBang/app/global/mail/service/MailAuthService.java
  src/main/java/JJinBBang/app/global/mail/service/MailSendService.java
  src/main/java/JJinBBang/app/global/mail/service/impl/MailAuthServiceImpl.java
  src/main/java/JJinBBang/app/global/security/filter/VerificationStatusFilter.java
  src/main/resources/application.yml
  src/test/java/JJinBBang/app/global/mail/MailAuthServiceImplTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test

#67 [FEAT #66] 액세스 토큰 재발급 API, 로그아웃 API 및 JwtUtils 모듈화/리팩토링
  src/main/java/JJinBBang/app/domain/user/controller/AuthController.java
  src/main/java/JJinBBang/app/domain/user/dto/response/ReissueAccessTokenResponse.java
  src/main/java/JJinBBang/app/global/jwt/JwtAuthenticationFilter.java
  src/main/java/JJinBBang/app/global/jwt/JwtUtils.java
  src/main/java/JJinBBang/app/global/jwt/enums/TokenType.java
  src/main/java/JJinBBang/app/global/jwt/exception/InvalidTokenException.java
  src/main/java/JJinBBang/app/global/jwt/repository/InMemoryRefreshTokenRepository.java
  src/main/java/JJinBBang/app/global/jwt/repository/RefreshTokenRepository.java
  src/main/java/JJinBBang/app/global/jwt/service/AbstractTokenGenerateService.java
  src/main/java/JJinBBang/app/global/jwt/service/RefreshTokenService.java
  src/main/java/JJinBBang/app/global/jwt/service/TokenGenerateService.java
  src/main/java/JJinBBang/app/global/jwt/service/impl/AccessTokenGenerateServiceImpl.java
  src/main/java/JJinBBang/app/global/jwt/service/impl/RefreshTokenGenerateServiceImpl.java
  src/main/java/JJinBBang/app/global/jwt/service/impl/SignupTokenGenerateServiceImpl.java
  src/main/java/JJinBBang/app/global/security/SecurityConfig.java
  src/main/java/JJinBBang/app/global/security/SecurityPathProperties.java
  src/main/resources/application.yml
  src/test/java/JJinBBang/app/global/util/AccessTokenGeneratorTest.java
  src/test/java/JJinBBang/app/global/util/JwtUtilsTest.java
Labels: ✨ Feature, 🔨 Refactor, ✅ Test
