Repository JJinBBang-web/JJinBBang_BE, pull requests merged in 2025-08, with the labels that each got.

#146 [Feat #145] 리뷰 및 건물 관련 API 권한 설정
  src/main/resources/application.yml
Labels: ✨ Feature

#149 Feat[#118]: 지도 검색 API BoundInfo 추가 및 공인중개사 조회 에러 해결
  src/main/java/JJinBBang/app/domain/building/repository/AgenciesRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/BuildingsRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/custom/AgenciesRepositoryCustom.java
  src/main/java/JJinBBang/app/domain/building/repository/custom/AgenciesRepositoryImpl.java
  src/main/java/JJinBBang/app/domain/building/repository/custom/BuildingsRepositoryCustom.java
  src/main/java/JJinBBang/app/domain/building/repository/custom/BuildingsRepositoryImpl.java
  src/main/java/JJinBBang/app/domain/building/service/SearchInfo.java
  src/main/java/JJinBBang/app/domain/map/controller/MapController.java
  src/main/java/JJinBBang/app/domain/map/service/MapService.java
  src/main/java/JJinBBang/app/domain/map/service/MapServiceImpl.java
  src/main/java/JJinBBang/app/global/common/dto/BoundInfo.java
  src/main/java/JJinBBang/app/global/common/dto/SearchInfoDto.java
Labels: ✨ Feature

#150 Bug[#119]: 공인중개사 조회 문제 해결 - 마커 조회하기, 내 주변 찐빵 API
  src/main/java/JJinBBang/app/domain/building/repository/custom/AgenciesRepositoryCustom.java
  src/main/java/JJinBBang/app/domain/building/repository/custom/AgenciesRepositoryImpl.java
  src/main/java/JJinBBang/app/domain/map/dto/request/NearByMapItemRequest.java
  src/main/java/JJinBBang/app/domain/map/exception/MapNotFoundException.java
  src/main/java/JJinBBang/app/domain/map/service/MapServiceImpl.java
  src/main/java/JJinBBang/app/global/common/dto/InfoDto.java
  src/main/java/JJinBBang/app/global/common/dto/MarkerInfo.java
  src/main/java/JJinBBang/app/global/common/dto/ReviewInfo.java
Labels: 🐞 Bug, ✨ Feature, 🔨 Refactor

#153 [Fix #152] 리뷰 작성 API 500 에러 해결
  src/main/java/JJinBBang/app/domain/building/dto/ReviewRequest.java
Labels: 🐞 Bug

#157 ✨ Feat[#156]: 캠퍼스 식별 방법 변경에 따른 API 수정
  src/main/java/JJinBBang/app/domain/building/repository/custom/BuildingsRepositoryCustom.java
  src/main/java/JJinBBang/app/domain/building/repository/custom/BuildingsRepositoryImpl.java
  src/main/java/JJinBBang/app/domain/common/dto/item/Filters.java
Labels: ✨ Feature, 🔨 Refactor

#164 [Feat #163]: 공인중개사 식별 방법 변경에 따른 API 수정
  src/main/java/JJinBBang/app/domain/building/dto/Building.java
  src/main/java/JJinBBang/app/domain/building/dto/BuildingRequest.java
  src/main/java/JJinBBang/app/domain/building/entity/Agencies.java
  src/main/java/JJinBBang/app/domain/building/repository/AgenciesRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/custom/BuildingsRepositoryImpl.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
  src/main/java/JJinBBang/app/domain/building/service/SearchInfo.java
Labels: ✨ Feature

#178 ♻️ Refactor[#177]: Building 엔티티 평균 월세, 평균 보증금, 평균 전세 필드 추가
  src/main/java/JJinBBang/app/domain/building/entity/Buildings.java
Labels: 🔨 Refactor

#190 [Fix #188]: 리뷰 요청의 크기 검증 로직에서 최소 크기를 1로 변경
  src/main/java/JJinBBang/app/domain/building/dto/ReviewRequest.java
Labels: 🐞 Bug

#197 [Fix #196]: 기숙사 유형 리뷰 작성 시 기숙사 합격 조건 관련 유효성 검사 삭제
  src/main/java/JJinBBang/app/domain/building/dto/Conditions.java
  src/main/java/JJinBBang/app/domain/building/dto/ReviewRequest.java
Labels: 🐞 Bug

#194 Fix[#189]: redirectUri null 검증 추가
  src/main/java/JJinBBang/app/domain/user/service/login/GoogleLoginServiceImpl.java
  src/main/java/JJinBBang/app/domain/user/service/login/KakaoLoginServiceImpl.java
  src/main/java/JJinBBang/app/domain/user/service/login/NaverLoginServiceImpl.java
Labels: 🐞 Bug

#198 Merge: develop -> release [08.28] - 2
  src/main/java/JJinBBang/app/domain/building/dto/Building.java
  src/main/java/JJinBBang/app/domain/building/dto/Conditions.java
  src/main/java/JJinBBang/app/domain/building/dto/ReviewRequest.java
  src/main/java/JJinBBang/app/domain/user/service/login/GoogleLoginServiceImpl.java
  src/main/java/JJinBBang/app/domain/user/service/login/KakaoLoginServiceImpl.java
  src/main/java/JJinBBang/app/domain/user/service/login/NaverLoginServiceImpl.java
Labels: 🌏 Deploy

#200 [Feat #199] 건물에 관한 평균 비용 계산 로직 추가
  src/main/java/JJinBBang/app/domain/building/dto/BuildingRequest.java
  src/main/java/JJinBBang/app/domain/building/entity/Buildings.java
  src/main/java/JJinBBang/app/domain/building/repository/ReviewsRepository.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
Labels: ✨ Feature

#201 Merge: develop -> release [08.29]
  src/main/java/JJinBBang/app/domain/building/dto/BuildingRequest.java
  src/main/java/JJinBBang/app/domain/building/entity/Buildings.java
  src/main/java/JJinBBang/app/domain/building/repository/ReviewsRepository.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
Labels: 🌏 Deploy

#203 [Fix #202]: 리뷰상세조회 시 좋아요 확인 로직을 사용자 ID 비교하는 방식으로 수정
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
Labels: 🐞 Bug
