Repository JJinBBang-web/JJinBBang_BE, pull requests merged in 2025-07, with the labels that each got.

#87 [Feat #56] 합격증명서, 재학증명서 인증을 위한 파일 제출 API
  .gitignore
  build.gradle
  src/main/java/JJinBBang/app/domain/user/controller/CertificateController.java
  src/main/java/JJinBBang/app/domain/user/dto/response/CertificateUserInfoResponse.java
  src/main/java/JJinBBang/app/domain/user/exception/CertificateBadRequestException.java
  src/main/java/JJinBBang/app/domain/user/exception/CertificateProcessException.java
  src/main/java/JJinBBang/app/domain/user/exception/UserAuthException.java
  src/main/java/JJinBBang/app/domain/user/repository/UsersRepository.java
  src/main/java/JJinBBang/app/domain/user/service/CertificateService.java
  src/main/java/JJinBBang/app/domain/user/service/CertificateServiceImpl.java
  src/main/java/JJinBBang/app/domain/user/service/UsersService.java
  src/main/java/JJinBBang/app/domain/user/service/UsersServiceImpl.java
  src/main/java/JJinBBang/app/global/config/GoogleApiConfig.java
  src/main/java/JJinBBang/app/global/config/GoogleProperties.java
Labels: ✨ Feature

#95 [Fix #94] ReviewsDetail 관련 빌드 오류 수정
  .gitignore
  src/main/java/JJinBBang/app/domain/building/dto/UserReviewResponse.java
  src/main/java/JJinBBang/app/domain/building/repository/CampusesRepository.java
  src/main/java/JJinBBang/app/domain/building/service/SearchInfo.java
  src/main/java/JJinBBang/app/domain/common/repository/CampusesRepository.java
  src/main/java/JJinBBang/app/domain/user/service/UsersServiceImpl.java
Labels: 🐞 Bug

#96 [BUG] develop -> release / ReviewsDetail 관련 빌드 오류 수정
  .gitignore
  src/main/java/JJinBBang/app/domain/building/dto/UserReviewResponse.java
  src/main/java/JJinBBang/app/domain/building/repository/CampusesRepository.java
  src/main/java/JJinBBang/app/domain/building/service/SearchInfo.java
  src/main/java/JJinBBang/app/domain/common/repository/CampusesRepository.java
  src/main/java/JJinBBang/app/domain/user/service/UsersServiceImpl.java
Labels: 🐞 Bug

#100 [FEAT] contractType ALL 타입 관련 코드 수정
  src/main/java/JJinBBang/app/domain/building/repository/BuildingsRepositoryImpl.java
  src/main/java/JJinBBang/app/domain/common/dto/item/Filters.java
  src/main/java/JJinBBang/app/domain/map/exception/MapUnprocessableException.java
  src/main/java/JJinBBang/app/domain/map/service/MapServiceImpl.java
Labels: ✨ Feature

#101 Feat[#77]: 내 주변 찐빵 API 구현
  src/main/java/JJinBBang/app/domain/map/controller/MapController.java
  src/main/java/JJinBBang/app/domain/map/dto/request/NearByMapItemRequest.java
  src/main/java/JJinBBang/app/domain/map/exception/MapNoContentException.java
  src/main/java/JJinBBang/app/domain/map/service/MapService.java
  src/main/java/JJinBBang/app/domain/map/service/MapServiceImpl.java
Labels: ✨ Feature

#112 [FEAT #108] 사용자 인증 상태 변경 API
  src/main/java/JJinBBang/app/domain/user/controller/AdminUserController.java
  src/main/java/JJinBBang/app/domain/user/controller/CertificateController.java
  src/main/java/JJinBBang/app/domain/user/dto/request/UpdateVerificationStatusDto.java
  src/main/java/JJinBBang/app/domain/user/exception/VerificatoinStatusException.java
  src/main/java/JJinBBang/app/domain/user/repository/UsersRepository.java
  src/main/java/JJinBBang/app/domain/user/service/CertificateService.java
  src/main/java/JJinBBang/app/domain/user/service/CertificateServiceImpl.java
  src/main/java/JJinBBang/app/domain/user/service/UsersService.java
  src/main/java/JJinBBang/app/domain/user/service/UsersServiceImpl.java
  src/main/java/JJinBBang/app/global/common/enums/VerificationStatus.java
Labels: ✨ Feature

#120 ✨ [Feat #98] Redis 방식 레포지토리 추가
  build.gradle
  src/main/java/JJinBBang/app/global/config/RedisConfig.java
  src/main/java/JJinBBang/app/global/jwt/repository/InMemoryRefreshTokenRepository.java
  src/main/java/JJinBBang/app/global/jwt/repository/RedisRefreshTokenRepository.java
  src/main/java/JJinBBang/app/global/mail/repository/InMemoryEmailAuthCodeRepository.java
  src/main/java/JJinBBang/app/global/mail/repository/RedisEmailAuthCodeRepository.java
  src/main/resources/application.yml
Labels: ✨ Feature, 🔨 Refactor

#133 [Feat #132] 공인중개사, 건물, 리뷰 관련 좋아요 수 관리 메서드 구현
  src/main/java/JJinBBang/app/domain/building/entity/Agencies.java
  src/main/java/JJinBBang/app/domain/building/entity/Buildings.java
  src/main/java/JJinBBang/app/domain/building/entity/Reviews.java
  src/main/java/JJinBBang/app/domain/building/repository/AgencyLikesRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/BuildingLikesRepository.java
  src/main/java/JJinBBang/app/domain/building/repository/ReviewLikesRepository.java
  src/main/java/JJinBBang/app/domain/building/service/BookmarkServiceImpl.java
Labels: 🐞 Bug, ✨ Feature

#130 :sparkles: Feat[#128] 네이버 로그인 API 개발
  src/main/java/JJinBBang/app/domain/user/exception/NaverAuthException.java
  src/main/java/JJinBBang/app/domain/user/service/login/NaverLoginServiceImpl.java
  src/main/resources/application.yml
Labels: ✨ Feature

#135 :sparkles: Feat[#134]: 토큰 재발급 시 리프레시 토큰도 함께 생성
  src/main/java/JJinBBang/app/domain/user/controller/AuthController.java
  src/main/java/JJinBBang/app/domain/user/dto/response/TokenResponse.java
  src/main/java/JJinBBang/app/global/jwt/service/impl/RefreshTokenGenerateServiceImpl.java
Labels: ✨ Feature

#123 [FEAT #110] 리뷰 건물 유형 이동 및 리뷰 생성,수정,삭제에 따른 건물의 건물 타입 동기화 로직 구현
  src/main/java/JJinBBang/app/domain/building/dto/ReviewDetailResponse.java
  src/main/java/JJinBBang/app/domain/building/dto/ReviewRequest.java
  src/main/java/JJinBBang/app/domain/building/dto/ReviewSummaryResponse.java
  src/main/java/JJinBBang/app/domain/building/dto/UserReviewResponse.java
  src/main/java/JJinBBang/app/domain/building/entity/AgencyReviews.java
  src/main/java/JJinBBang/app/domain/building/entity/Buildings.java
  src/main/java/JJinBBang/app/domain/building/entity/DormReviews.java
  src/main/java/JJinBBang/app/domain/building/entity/GeneralReviews.java
  src/main/java/JJinBBang/app/domain/building/entity/ReviewDetails.java
  src/main/java/JJinBBang/app/domain/building/entity/Reviews.java
  src/main/java/JJinBBang/app/domain/building/repository/ReviewsRepository.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
  src/main/java/JJinBBang/app/domain/building/service/SearchInfo.java
  src/main/java/JJinBBang/app/global/common/dto/GeneralReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/InfoDto.java
Labels: ✨ Feature

#138 [BUG] REVIEW 조회 안되는 문제 및 기숙사, 공인중개사 출력 관련 문제
  src/main/java/JJinBBang/app/domain/map/service/MapServiceImpl.java
Labels: 🐞 Bug
