Repository JJinBBang-web/JJinBBang_BE, pull requests merged in 2025-09, with the labels that each got.

#206 [Feat #205]: 건물 유형 추가 및 업데이트 로직 변경
  src/main/java/JJinBBang/app/domain/building/entity/Buildings.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
Labels: ✨ Feature

#208 [Feat #207] S3 Presigned 업로드 API 추가 및 리뷰 삭제 시 이미지 정리 구현
  build.gradle
  src/main/java/JJinBBang/app/domain/building/entity/Buildings.java
  src/main/java/JJinBBang/app/domain/building/exception/ReviewNotFoundException.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
  src/main/java/JJinBBang/app/domain/common/config/S3Config.java
  src/main/java/JJinBBang/app/domain/common/controller/S3Controller.java
  src/main/java/JJinBBang/app/domain/common/dto/PresignedUrlResponse.java
  src/main/java/JJinBBang/app/domain/common/service/S3Service.java
  src/main/resources/application.yml
Labels: ✨ Feature

#209 Merge: develop -> release [09.01]
  build.gradle
  src/main/java/JJinBBang/app/domain/building/entity/Buildings.java
  src/main/java/JJinBBang/app/domain/building/exception/ReviewNotFoundException.java
  src/main/java/JJinBBang/app/domain/building/service/ReviewServiceImpl.java
  src/main/java/JJinBBang/app/domain/common/config/S3Config.java
  src/main/java/JJinBBang/app/domain/common/controller/S3Controller.java
  src/main/java/JJinBBang/app/domain/common/dto/PresignedUrlResponse.java
  src/main/java/JJinBBang/app/domain/common/service/S3Service.java
  src/main/resources/application.yml
Labels: 🌏 Deploy

#211 [Fix #210]: 리뷰 상세 조회 API 오류 해결
  src/main/java/JJinBBang/app/domain/building/dto/ReviewDetailResponse.java
  src/main/java/JJinBBang/app/domain/building/dto/ReviewImages.java
Labels: 🐞 Bug

#218 Feat[#147] 보안 경로 매칭 구조 개편 - HTTP 메서드 분기 및 경로설정 파일 외부화
  .gitignore
  src/main/java/JJinBBang/app/global/jwt/JwtAuthenticationFilter.java
  src/main/java/JJinBBang/app/global/security/CompiledSecurityPathMatcher.java
  src/main/java/JJinBBang/app/global/security/SecurityConfig.java
  src/main/java/JJinBBang/app/global/security/SecurityPathMatchUtil.java
  src/main/java/JJinBBang/app/global/security/SecurityPathProperties.java
  src/main/java/JJinBBang/app/global/security/filter/PendingUserFilter.java
  src/main/java/JJinBBang/app/global/security/filter/VerificationStatusFilter.java
  src/main/resources/application.yml
Labels: ✨ Feature

#227 🐛 Fix[#226]: NPE 에러 해결 및 검증
  src/main/java/JJinBBang/app/domain/building/service/SearchInfo.java
  src/main/java/JJinBBang/app/global/common/dto/AgencyReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/SearchInfoDto.java
Labels: 🐞 Bug

#228 Merge: develop -> release [09.13]
  src/main/java/JJinBBang/app/domain/building/dto/GeneralReviewDto.java
  src/main/java/JJinBBang/app/domain/building/entity/Reviews.java
  src/main/java/JJinBBang/app/domain/building/service/SearchInfo.java
  src/main/java/JJinBBang/app/global/common/dto/AgencyReviewInfo.java
  src/main/java/JJinBBang/app/global/common/dto/SearchInfoDto.java
Labels: 🌈 ALL

#233 Merge: develop -> release [09.24]
  build.gradle
  src/main/java/JJinBBang/app/domain/common/controller/.gitkeep
  src/main/java/JJinBBang/app/domain/common/exception/.gitkeep
  src/main/java/JJinBBang/app/domain/common/repository/.gitkeep
  src/main/java/JJinBBang/app/domain/common/service/.gitkeep
  src/main/resources/application.yml
Labels: 🌈 ALL
